baseURL = "https://www.botkube.io/"
languageCode = "en-us"
title = "BotKube"
theme = "hugo-theme-learn"
description = "BotKube is your Kubernetes bot"
Paginate = 4
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  author = "InfraCloud" # add your company name
  github = "https://github.com/infracloudio/botkube" # add your github profile name
  email = "info@infracloud.io"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  disableLanguageSwitchingButton = true
  themeVariant = "blue"

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-slack'></i> Community Slack"
url = "http://join.botkube.io"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/infracloudio/botkube"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Privacy Policy"
url = "/privacy"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-contract '></i> License"
url = "/license"
weight = 40

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-question-circle'></i> Support"
url = "/support"
weight = 50

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-twitter'></i> Twitter"
url = "https://twitter.com/infracloudio"
weight = 60
